[2021-05-12 10:49:01,263] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task3 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 10:49:01,271] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task3 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 10:49:01,271] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 10:49:01,271] {taskinstance.py:1069} INFO - Starting attempt 2 of 3
[2021-05-12 10:49:01,271] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 10:49:01,463] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task3> on 2021-05-12T10:39:48.267484+00:00
[2021-05-12 10:49:01,466] {standard_task_runner.py:52} INFO - Started process 2186538 to run task
[2021-05-12 10:49:01,471] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task3', '2021-05-12T10:39:48.267484+00:00', '--job-id', '66', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmpxlb7mvli', '--error-file', '/tmp/tmp4sagb9rv']
[2021-05-12 10:49:01,471] {standard_task_runner.py:77} INFO - Job 66: Subtask task3
[2021-05-12 10:49:01,593] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task3 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-12 10:49:01,850] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task3
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-12 10:49:01,850] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-12 10:49:01,851] {bash.py:158} INFO - Running command: echo im task 3!!!!!!!!!!!!!!!!!!!!!! exit 1
[2021-05-12 10:49:01,858] {bash.py:169} INFO - Output:
[2021-05-12 10:49:01,859] {bash.py:173} INFO - im task 3!!!!!!!!!!!!!!!!!!!!!! exit 1
[2021-05-12 10:49:01,859] {bash.py:177} INFO - Command exited with return code 0
[2021-05-12 10:49:01,966] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task3, execution_date=20210512T103948, start_date=20210512T104901, end_date=20210512T104901
[2021-05-12 10:49:02,262] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-12 10:49:02,291] {local_task_job.py:146} INFO - Task exited with return code 0
