[2021-05-12 11:05:29,165] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task3 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 11:05:29,172] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task3 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 11:05:29,173] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 11:05:29,173] {taskinstance.py:1069} INFO - Starting attempt 6 of 7
[2021-05-12 11:05:29,173] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 11:05:29,290] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task3> on 2021-05-12T10:39:48.267484+00:00
[2021-05-12 11:05:29,293] {standard_task_runner.py:52} INFO - Started process 2197022 to run task
[2021-05-12 11:05:29,298] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task3', '2021-05-12T10:39:48.267484+00:00', '--job-id', '87', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmpqzobco9a', '--error-file', '/tmp/tmpavvqub4u']
[2021-05-12 11:05:29,298] {standard_task_runner.py:77} INFO - Job 87: Subtask task3
[2021-05-12 11:05:29,445] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task3 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-12 11:05:29,570] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task3
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-12 11:05:29,570] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-12 11:05:29,571] {bash.py:158} INFO - Running command: echo im task 3!!!!!!!!!!!!!!!!!!!!!! || exit 1
[2021-05-12 11:05:29,585] {bash.py:169} INFO - Output:
[2021-05-12 11:05:29,586] {bash.py:173} INFO - im task 3!!!!!!!!!!!!!!!!!!!!!!
[2021-05-12 11:05:29,587] {bash.py:177} INFO - Command exited with return code 0
[2021-05-12 11:05:29,710] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task3, execution_date=20210512T103948, start_date=20210512T110529, end_date=20210512T110529
[2021-05-12 11:05:29,940] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-12 11:05:29,964] {local_task_job.py:146} INFO - Task exited with return code 0
