[2021-05-12 11:58:14,679] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 11:58:14,687] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 11:58:14,688] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 11:58:14,688] {taskinstance.py:1069} INFO - Starting attempt 15 of 16
[2021-05-12 11:58:14,688] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 11:58:14,802] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task2> on 2021-05-12T10:39:48.267484+00:00
[2021-05-12 11:58:14,805] {standard_task_runner.py:52} INFO - Started process 2231095 to run task
[2021-05-12 11:58:14,811] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task2', '2021-05-12T10:39:48.267484+00:00', '--job-id', '122', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmp5hqxhtcm', '--error-file', '/tmp/tmpc_ji15jg']
[2021-05-12 11:58:14,812] {standard_task_runner.py:77} INFO - Job 122: Subtask task2
[2021-05-12 11:58:14,964] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-12 11:58:15,080] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-12 11:58:15,080] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-12 11:58:15,081] {bash.py:158} INFO - Running command: echo im task 2 !!!!!!!!!!!!!!!!!!!! || exit 1
[2021-05-12 11:58:15,088] {bash.py:169} INFO - Output:
[2021-05-12 11:58:15,090] {bash.py:173} INFO - im task 2 !!!!!!!!!!!!!!!!!!!!
[2021-05-12 11:58:15,090] {bash.py:177} INFO - Command exited with return code 0
[2021-05-12 11:58:15,299] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task2, execution_date=20210512T103948, start_date=20210512T115814, end_date=20210512T115815
[2021-05-12 11:58:15,620] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-12 11:58:15,663] {local_task_job.py:146} INFO - Task exited with return code 0
