[2021-05-13 04:51:15,996] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:51:16,004] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:51:16,005] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:51:16,005] {taskinstance.py:1069} INFO - Starting attempt 20 of 21
[2021-05-13 04:51:16,005] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:51:16,146] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task2> on 2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:51:16,148] {standard_task_runner.py:52} INFO - Started process 2895951 to run task
[2021-05-13 04:51:16,157] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task2', '2021-05-12T10:39:48.267484+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmp0tiz3gh3', '--error-file', '/tmp/tmp0nnpz3za']
[2021-05-13 04:51:16,157] {standard_task_runner.py:77} INFO - Job 149: Subtask task2
[2021-05-13 04:51:16,286] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-13 04:51:16,449] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:51:16,449] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 04:51:16,450] {bash.py:158} INFO - Running command: echo im task 2 !!!!!!!!!!!!!!!!!!!! || exit 1
[2021-05-13 04:51:16,457] {bash.py:169} INFO - Output:
[2021-05-13 04:51:16,463] {bash.py:173} INFO - im task 2 !!!!!!!!!!!!!!!!!!!!
[2021-05-13 04:51:16,464] {bash.py:177} INFO - Command exited with return code 0
[2021-05-13 04:51:16,783] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task2, execution_date=20210512T103948, start_date=20210513T045115, end_date=20210513T045116
[2021-05-13 04:51:17,087] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-13 04:51:17,127] {local_task_job.py:146} INFO - Task exited with return code 0
