[2021-05-13 04:52:54,362] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:52:54,371] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:52:54,371] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:52:54,371] {taskinstance.py:1069} INFO - Starting attempt 21 of 22
[2021-05-13 04:52:54,371] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:52:54,544] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task2> on 2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:52:54,548] {standard_task_runner.py:52} INFO - Started process 2896901 to run task
[2021-05-13 04:52:54,556] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task2', '2021-05-12T10:39:48.267484+00:00', '--job-id', '152', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmpkbj6hhjk', '--error-file', '/tmp/tmpyq_67335']
[2021-05-13 04:52:54,557] {standard_task_runner.py:77} INFO - Job 152: Subtask task2
[2021-05-13 04:52:54,747] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task2 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-13 04:52:54,889] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task2
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:52:54,890] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 04:52:54,890] {bash.py:158} INFO - Running command: echo im task 2 !!!!!!!!!!!!!!!!!!!! || exit 1
[2021-05-13 04:52:54,898] {bash.py:169} INFO - Output:
[2021-05-13 04:52:54,900] {bash.py:173} INFO - im task 2 !!!!!!!!!!!!!!!!!!!!
[2021-05-13 04:52:54,900] {bash.py:177} INFO - Command exited with return code 0
[2021-05-13 04:52:55,014] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task2, execution_date=20210512T103948, start_date=20210513T045254, end_date=20210513T045255
[2021-05-13 04:52:55,286] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-13 04:52:55,329] {local_task_job.py:146} INFO - Task exited with return code 0
