[2021-05-13 04:49:58,331] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:49:58,339] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:49:58,339] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:49:58,339] {taskinstance.py:1069} INFO - Starting attempt 13 of 14
[2021-05-13 04:49:58,339] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:49:58,697] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task4> on 2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:49:58,700] {standard_task_runner.py:52} INFO - Started process 2894862 to run task
[2021-05-13 04:49:58,705] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task4', '2021-05-12T10:39:48.267484+00:00', '--job-id', '141', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmpv837ud1z', '--error-file', '/tmp/tmpfv002o57']
[2021-05-13 04:49:58,706] {standard_task_runner.py:77} INFO - Job 141: Subtask task4
[2021-05-13 04:49:59,134] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-13 04:49:59,329] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task4
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:49:59,330] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 04:49:59,330] {bash.py:158} INFO - Running command: airflow tasks clear -f status_test -y
[2021-05-13 04:49:59,337] {bash.py:169} INFO - Output:
[2021-05-13 04:50:00,531] {bash.py:173} INFO - [2021-05-13 04:50:00,530] {dagbag.py:451} INFO - Filling up the DagBag from /root/airflow/dags
[2021-05-13 04:50:00,546] {bash.py:173} INFO - /home/ubuntu/venv/lib/python3.8/site-packages/airflow/utils/decorators.py:94 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2021-05-13 04:50:01,031] {bash.py:177} INFO - Command exited with return code 0
[2021-05-13 04:50:01,234] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task4, execution_date=20210512T103948, start_date=20210513T044958, end_date=20210513T045001
[2021-05-13 04:50:01,399] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-13 04:50:01,409] {local_task_job.py:146} INFO - Task exited with return code 0
