[2021-05-13 04:52:49,288] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:52:49,296] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-13 04:52:49,296] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:52:49,296] {taskinstance.py:1069} INFO - Starting attempt 17 of 18
[2021-05-13 04:52:49,296] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 04:52:49,419] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task4> on 2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:52:49,422] {standard_task_runner.py:52} INFO - Started process 2896828 to run task
[2021-05-13 04:52:49,427] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task4', '2021-05-12T10:39:48.267484+00:00', '--job-id', '151', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmppbvv4gp6', '--error-file', '/tmp/tmpe6txch9t']
[2021-05-13 04:52:49,428] {standard_task_runner.py:77} INFO - Job 151: Subtask task4
[2021-05-13 04:52:49,552] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-13 04:52:49,672] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task4
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-13 04:52:49,673] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 04:52:49,673] {bash.py:158} INFO - Running command: airflow tasks clear -f status_test -y
[2021-05-13 04:52:49,681] {bash.py:169} INFO - Output:
[2021-05-13 04:52:51,170] {bash.py:173} INFO - [2021-05-13 04:52:51,169] {dagbag.py:451} INFO - Filling up the DagBag from /root/airflow/dags
[2021-05-13 04:52:51,185] {bash.py:173} INFO - /home/ubuntu/venv/lib/python3.8/site-packages/airflow/utils/decorators.py:94 DeprecationWarning: provide_context is deprecated as of 2.0 and is no longer required
[2021-05-13 04:52:51,647] {bash.py:177} INFO - Command exited with return code 0
[2021-05-13 04:52:51,792] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task4, execution_date=20210512T103948, start_date=20210513T045249, end_date=20210513T045251
[2021-05-13 04:52:51,984] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-13 04:52:52,029] {local_task_job.py:146} INFO - Task exited with return code 0
