[2021-05-12 10:57:01,175] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 10:57:01,183] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [queued]>
[2021-05-12 10:57:01,183] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 10:57:01,183] {taskinstance.py:1069} INFO - Starting attempt 4 of 5
[2021-05-12 10:57:01,183] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-12 10:57:01,389] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): task4> on 2021-05-12T10:39:48.267484+00:00
[2021-05-12 10:57:01,391] {standard_task_runner.py:52} INFO - Started process 2191707 to run task
[2021-05-12 10:57:01,397] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'status_test', 'task4', '2021-05-12T10:39:48.267484+00:00', '--job-id', '73', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/task_status.py', '--cfg-path', '/tmp/tmpn3pt3gho', '--error-file', '/tmp/tmpjla4px5l']
[2021-05-12 10:57:01,397] {standard_task_runner.py:77} INFO - Job 73: Subtask task4
[2021-05-12 10:57:01,536] {logging_mixin.py:104} INFO - Running <TaskInstance: status_test.task4 2021-05-12T10:39:48.267484+00:00 [running]> on host sdn-k8s-b2-3-3.maas
[2021-05-12 10:57:01,692] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=davidwu5858@gmail.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=status_test
AIRFLOW_CTX_TASK_ID=task4
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T10:39:48.267484+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-12T10:39:48.267484+00:00
[2021-05-12 10:57:01,692] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-12 10:57:01,693] {bash.py:158} INFO - Running command: echo im task 4!!!!!!!!!!!!!!!!!!!!!!
[2021-05-12 10:57:01,699] {bash.py:169} INFO - Output:
[2021-05-12 10:57:01,701] {bash.py:173} INFO - im task 4!!!!!!!!!!!!!!!!!!!!!!
[2021-05-12 10:57:01,701] {bash.py:177} INFO - Command exited with return code 0
[2021-05-12 10:57:01,825] {taskinstance.py:1185} INFO - Marking task as SUCCESS. dag_id=status_test, task_id=task4, execution_date=20210512T103948, start_date=20210512T105701, end_date=20210512T105701
[2021-05-12 10:57:01,964] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-12 10:57:02,008] {local_task_job.py:146} INFO - Task exited with return code 0
